###########--------------------------------------------------------------------###########
#           WGCNA Module Preservation Analysis
#           Salt Stress Response in Chlamydomonas reinhardtii
#
#  This script performs module preservation analysis comparing the
#  original network structure against a null model generated by permuting time
#  points within genes, maintaining expression distributions while disrupting
#  temporal structure to assess statistical significance of module stability. 
#
#  Script for: Integrating co-expression network analysis and machine learning to reveal 
#  the regulatory landscape of GPD genes in Chlamydomonas reinhardtii under salinity stress
#
#  Authors: Tzec-Interián et al.
#  Date: October 2025
#
###########--------------------------------------------------------------------###########

library(WGCNA)
library(ggplot2)
library(dplyr)
library(pheatmap)

condition_prefix <- "salt"
date_export <- format(Sys.Date(), "%Y%m%d")

###########----------------------- 1. Data Loading and Verification ---------------

# Load required objects from WGCNA analysis
required_objects <- c("datExpr", "module_colors_assigned", "soft_power_val")
missing_objects <- required_objects[!sapply(required_objects, exists)]

if (length(missing_objects) > 0) {
  stop("Missing required objects from WGCNA analysis: ", 
       paste(missing_objects, collapse = ", "), 
       "\nPlease run Cre_Salt_WGCNA.R first or load the RData session.")
}

moduleColors <- module_colors_assigned

message("Required objects found.")
message("datExpr dimensions: ", paste(dim(datExpr), collapse = " x "))
message("Number of modules: ", length(unique(moduleColors)))

###########----------------------- 2. Test Dataset Generation ---------------

# Generate permuted test dataset by shuffling time points within each gene
# This approach disrupts temporal structure while preserving gene-level expression
# distributions, creating an appropriate null model for preservation analysis

set.seed(1234)
datExpr_test <- apply(datExpr, 2, sample)
datExpr_test <- as.data.frame(datExpr_test)
rownames(datExpr_test) <- rownames(datExpr)

message("Permuted test dataset generated.")
message("Original data dimensions: ", paste(dim(datExpr), collapse = " x "))
message("Permuted data dimensions: ", paste(dim(datExpr_test), collapse = " x "))

###########----------------------- 3. Module Preservation Analysis ---------------

# Prepare multiData and multiColor objects for modulePreservation function
multiExpr <- list(
  ref = list(data = datExpr),
  test = list(data = datExpr_test)
)

multiColor <- list(ref = moduleColors)

# Perform module preservation analysis using signed hybrid network type
# and 100 permutations to balance statistical power with computational efficiency
mp <- modulePreservation(
  multiExpr,
  multiColor = multiColor,
  networkType = "signed hybrid",
  nPermutations = 100,
  randomSeed = 1234,
  verbose = 3
)

message("Module preservation analysis completed.")

###########----------------------- 4. Module Eigengene Correlation Analysis ---------------

# Compare module eigengenes between original and permuted data to assess
# the impact of permutation on module structure
MEList_orig <- moduleEigengenes(datExpr, colors = moduleColors)
MEs_orig <- MEList_orig$eigengenes

MEList_perm <- moduleEigengenes(datExpr_test, colors = moduleColors)
MEs_perm <- MEList_perm$eigengenes

corME <- cor(MEs_orig, MEs_perm)

# Clean module names and create visualization labels
module_names_clean <- gsub("^ME", "", colnames(corME))
rownames(corME) <- paste0(module_names_clean, "_orig")
colnames(corME) <- paste0(module_names_clean, "_perm")

# Visualize correlation between original and permuted module eigengenes
pheatmap(corME,
         main = "Module Eigengene Correlation: Original vs Permuted",
         color = colorRampPalette(c("blue", "white", "red"))(100),
         display_numbers = TRUE,
         number_format = "%.2f",
         fontsize_number = 6,
         fontsize_row = 8,
         fontsize_col = 8,
         cluster_rows = FALSE,
         cluster_cols = FALSE)

###########----------------------- 5. Preservation Statistics Extraction ---------------

# Extract key preservation statistics from modulePreservation results
zstats <- mp$preservation$Z$ref.ref$inColumnsAlsoPresentIn.test
medianRankstats <- mp$preservation$observed$ref.ref$inColumnsAlsoPresentIn.test

Zsummary <- zstats[, "Zsummary.pres"]
medianRank <- medianRankstats[, "medianRank.pres"]

# Create summary table with preservation statistics
preservation_summary <- data.frame(
  Module = rownames(zstats),
  Zsummary = Zsummary,
  medianRank = medianRank,
  Interpretation = ifelse(Zsummary > 10, "Strong",
                         ifelse(Zsummary > 2, "Moderate", "Weak"))
)

# Sort by Zsummary (descending order)
preservation_summary <- preservation_summary %>%
  arrange(desc(Zsummary))

message("Preservation statistics extracted.")
message("Top 5 most preserved modules:")
print(head(preservation_summary, 5))

###########----------------------- 6. Preservation Statistics Visualization ---------------

# Prepare data for visualization with modules sorted by preservation score
orderZ <- order(Zsummary, decreasing = TRUE)
Zsummary_sorted <- Zsummary[orderZ]
moduleNames_sorted <- rownames(zstats)[orderZ]
moduleColors_sorted <- moduleNames_sorted

# Create and save preservation plot as PDF
pdf(paste0(date_export, "_", condition_prefix, "_ModulePreservation_barplot.pdf"), 
    width = 10, height = 6)
par(mar = c(8, 4, 4, 2))
barplot(Zsummary_sorted,
        names.arg = moduleNames_sorted,
        col = moduleColors_sorted,
        las = 2,
        cex.names = 1.0,
        cex.lab = 1.2,
        cex.axis = 1.1,
        ylab = "Z-summary Preservation Score",
        ylim = c(min(Zsummary_sorted) - 0.5, max(Zsummary_sorted) + 2))

# Add reference lines for interpretation
abline(h = 2, col = "red", lty = 2)
abline(h = 10, col = "darkgreen", lty = 2)
legend("topright", legend = c("Z < 2 = Not preserved", "Z > 10 = Strong preservation"),
       col = c("red", "darkgreen"), lty = 2, bty = "n")
dev.off()

###########----------------------- 7. Results Export ---------------

# Save complete preservation results for detailed analysis
saveRDS(mp, 
        file = paste0(date_export, "_", condition_prefix, "_ModulePreservation_FullResults.rds"))

message("Complete preservation results saved.")

###########----------------------- 8. Session Information Export ---------------

# Export computational environment details

session_info_output <- sessionInfo()

sink(paste0(date_export, "_", condition_prefix, "_ModulePreservation_SessionInfo.txt"))
print(session_info_output)
sink()

saveRDS(session_info_output, 
        file = paste0(date_export, "_", condition_prefix, "_ModulePreservation_SessionInfo.rds"))

loaded_packages <- session_info_output$otherPkgs
base_packages <- session_info_output$basePkgs

package_versions_df <- data.frame(
  Package = c(names(loaded_packages), base_packages),
  Version = c(sapply(loaded_packages, function(x) as.character(x$Version)), 
              rep("base", length(base_packages))),
  stringsAsFactors = FALSE
)

write.csv(package_versions_df, 
          file = paste0(date_export, "_", condition_prefix, "_ModulePreservation_PackageVersions.csv"),
          row.names = FALSE)

# Save complete session
save.image(file = paste0(date_export, "_", condition_prefix, "_ModulePreservation_session.RData"))

message("Session information exported.")
message("Module preservation analysis completed successfully.")

